name: Python Setup Database

on:
  # Trigger workflow on push to main branch
  push:
    branches:
      - main

  # Optionally, trigger workflow on a schedule (e.g., every 24 hours)
  schedule:
    - cron: "0 0 * * *"  # This runs every day at midnight

jobs:
  setup-db:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies listed in a requirements file

    # Step 4: Run the setup_db.py script
    - name: Run setup_db.py
      run: |
        python setup_db.py
