name: Stock Tracker

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  stock_tracking:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        python setup_db.py  # Create the 'portfolio' table

    - name: Run the stock tracking scripts
      run: |
        python add_stock.py  # Add predefined stocks to the portfolio
        python stock_tracker.py  # Fetch stock prices and update database
