name: Stock Tracker Workflow

# Trigger the workflow manually via the GitHub UI
on:
  workflow_dispatch:

jobs:
  stock-tracker:
    runs-on: ubuntu-latest  # Specify the environment to run the job

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install the required libraries from requirements.txt

    # Step 4: Set up the database (optional)
    - name: Set up database
      run: |
        python setup_db.py  # Initialize the database, if necessary

    # Step 5: Add stocks to the portfolio (optional)
    - name: Add stocks to portfolio
      run: |
        python add_stock.py  # Add stocks to the portfolio (you can also add a hardcoded list here)

    # Step 6: Fetch stock data and update portfolio
    - name: Track stock prices
      run: |
        python stock_tracker.py  # Fetch stock data using yfinance and update the portfolio

    # Step 7: (Optional) Save the updated portfolio.db or generate reports, etc.
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add portfolio.db
        git commit -m "Updated portfolio with latest stock data"
        git push
